### ISSUE TITLE
Where do I find CWSI plugin once installed?

### ISSUE THREAD

**Issue by Matesanz** [FloEll/CWSI#1]
Hello, thank you for your time and work, I'm trying to calculate CWSI values using your plugin in QGIS 3.18.

Once installed, **how can I start and use your plugin?**

Thank you again.
Have a nice day. :smile:

**Comment by Matesanz** [comment]
Sorry just found out that I didn't activate it. :pensive: new to QGIS...

**Comment by FloEll** [comment]
Hi, no problem :) I'm happy you are trying the Plugin. Just write me if you encounter any problems. Cheers!
