### ISSUE TITLE
Qgis Python Error

### ISSUE THREAD

**Issue by ereenozdemir** [FloEll/CWSI#2]
Hey,
I hope you're okey and everything fine with you. :)

I have a problem with your code. When i use this plugin on QGIS, I am encountering this error : "An error has occurred while executing Python code: See message log (Python Error) for more details."

Have u any suggestions about this error ?

Best

**Comment by FloEll** [comment]
Dear ereenozdemir, 
I'm sorry that you are encountering problems with the CWSI plugin. I think your error message is pointing you towards the actual error message in the python-error tab. I guess this message pops up on the upper site of your screen right? Then you can click on 'show error' and the protocol should be visible on the lower side of your QGIS canvas. 
Can you click on the python error tab there and copy this error message? It could look something like this: 
 File "C:/Users/Your_Computer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cwsi\cwsi.py", line 225, in read_lst_img
self.dlg.lst = new_raster.GetRasterBand(1).ReadAsArray()
AttributeError: 'NoneType' object has no attribute 'GetRasterBand'

With this error message I can try to help you. 
Btw. I'm planning to publish a new version of the CWSI plugin next week or so, so if you have anything that you woul wish for in the new version, just tell me :) 
Cheers :)

**Comment by ereenozdemir** [comment]
Thanks for answering. 
Yes, that's the error message I was talking about. How can i fix ? :) 
Btw congrulations your new version. Maybe you can explain how to use the plugin with screenshots :)

**Comment by FloEll** [comment]
thanks, yes, the plan is to create a tutorial with screenshots, but it might still take a few weeks until this is uploaded sry. 
So you are getting: AttributeError: 'NoneType' object has no attribute 'GetRasterBand' ? 
In this case something is wrong either with your input path or with your image. Can you check your input path? And if that does not work, you can also send me a link to one of your input images, I can test it and figure out why it doesn't work.

**Comment by ereenozdemir** [comment]
Sure link is here : 
https://landsatlook.usgs.gov/browse/collection02/level-1/standard/oli-tirs/2021/181/032/LC08_L1TP_181032_20210711_20210711_02_RT/LC08_L1TP_181032_20210711_20210711_02_RT_tir.tif?requestSignature=eyJjb250YWN0SWQiOjI0NTAyOTIzLCJkb3dubG9hZElkIjo1MTQ1MDk0OCwiZGF0ZUdlbmVyYXRlZCI6IjIwMjEtMDctMTNUMDk6MjE6MzYtMDU6MDAiLCJzaWduYXR1cmUiOiIkNSQkZjJ5YXpxVUI2T2ZjbzVHZ1lCVzJYSHVjeGt1YmdwbGMxdHdZZ1ZWOXRwNiJ9

Thanks for helping btw. :)

**Comment by FloEll** [comment]
Ok, great thanks! So the CWSI Plugin expects a single channel/band raster. Your raster has a data channel, and an alpha channel. You can erase the alpha Channel e.g. using the rearrange band algorithm in QGIS3. Here is a topic on this: https://gis.stackexchange.com/questions/339779/detecting-and-deleting-alpha-mark-in-qgis
Hope that helped!

**Comment by ereenozdemir** [comment]
Yesss :) I understand what you mean. Thanks a lot.!
Now, I'm waiting your new update :)
Best.

**Comment by FloEll** [comment]
Haha ok :)  did it work with the one band raster then?

**Comment by ereenozdemir** [comment]
Yes! It's working :) Thanks a lot
